### ISSUE TITLE
CI failure: After restarting the controller, the controller is not ready for a certain period of time.

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#1030]
Copy-paste the link of the CI build where that test failure has happen.
https://github.com/spidernet-io/spiderpool/actions/runs/3444188595/jobs/5746601051

Upload the zip file generated from that test failure.
[dualstack-debuglog.txt (1).zip](https://github.com/spidernet-io/spiderpool/files/9998946/dualstack-debuglog.txt.1.zip)

```
-------- kubectl get pod -A -o wide
NAMESPACE          NAME                                                         READY   STATUS             RESTARTS      AGE    IP              NODE                                 NOMINATED NODE   READINESS GATES   LABELS
default            test-pod-7cb5585489-ncphw                                    1/1     Running            0             11m    172.18.40.132   spiderpool1111101355-worker          <none>           <none>            app=test-pod,pod-template-hash=7cb5585489
kube-system        coredns-565d847f94-4gk5p                                     1/1     Running            0             11m    172.18.40.155   spiderpool1111101355-control-plane   <none>           <none>            k8s-app=kube-dns,pod-template-hash=565d847f94
kube-system        coredns-565d847f94-vntzm                                     1/1     Running            0             11m    172.18.40.172   spiderpool1111101355-worker          <none>           <none>            k8s-app=kube-dns,pod-template-hash=565d847f94
kube-system        etcd-spiderpool1111101355-control-plane                      1/1     Running            0             13m    172.18.0.3      spiderpool1111101355-control-plane   <none>           <none>            component=etcd,tier=control-plane
kube-system        kube-apiserver-spiderpool1111101355-control-plane            1/1     Running            0             13m    172.18.0.3      spiderpool1111101355-control-plane   <none>           <none>            component=kube-apiserver,tier=control-plane
kube-system        kube-controller-manager-spiderpool1111101355-control-plane   1/1     Running            0             13m    172.18.0.3      spiderpool1111101355-control-plane   <none>           <none>            component=kube-controller-manager,tier=control-plane
kube-system        kube-multus-ds-477w2                                         1/1     Running            0             11m    172.18.0.3      spiderpool1111101355-control-plane   <none>           <none>            app=multus,controller-revision-hash=67dffbbcb7,name=multus,pod-template-generation=1,tier=node
kube-system        kube-multus-ds-vxt87                                         1/1     Running            0             11m    172.18.0.2      spiderpool1111101355-worker          <none>           <none>            app=multus,controller-revision-hash=67dffbbcb7,name=multus,pod-template-generation=1,tier=node
kube-system        kube-proxy-8svxs                                             1/1     Running            0             13m    172.18.0.3      spiderpool1111101355-control-plane   <none>           <none>            controller-revision-hash=7ccf78d585,k8s-app=kube-proxy,pod-template-generation=1
kube-system        kube-proxy-ltv6t                                             1/1     Running            0             13m    172.18.0.2      spiderpool1111101355-worker          <none>           <none>            controller-revision-hash=7ccf78d585,k8s-app=kube-proxy,pod-template-generation=1
kube-system        kube-scheduler-spiderpool1111101355-control-plane            1/1     Running            0             13m    172.18.0.3      spiderpool1111101355-control-plane   <none>           <none>            component=kube-scheduler,tier=control-plane
kube-system        spiderpool-agent-8wqzr                                       1/1     Running            0             12m    172.18.0.2      spiderpool1111101355-worker          <none>           <none>            app.kubernetes.io/component=spiderpool-agent,app.kubernetes.io/instance=spiderpool,app.kubernetes.io/name=spiderpool,controller-revision-hash=5bb8d8f54b,pod-template-generation=1
kube-system        spiderpool-agent-k6c68                                       1/1     Running            0             12m    172.18.0.3      spiderpool1111101355-control-plane   <none>           <none>            app.kubernetes.io/component=spiderpool-agent,app.kubernetes.io/instance=spiderpool,app.kubernetes.io/name=spiderpool,controller-revision-hash=5bb8d8f54b,pod-template-generation=1
kube-system        spiderpool-controller-6f6fc9fd5d-dlqqc                       0/1     CrashLoopBackOff   3 (23s ago)   2m3s   172.18.0.3      spiderpool1111101355-control-plane   <none>           <none>            app.kubernetes.io/component=spiderpool-controller,app.kubernetes.io/instance=spiderpool,app.kubernetes.io/name=spiderpool,pod-template-hash=6f6fc9fd5d
kube-system        spiderpool-controller-6f6fc9fd5d-ngbr6                       0/1     CrashLoopBackOff   3 (4s ago)    2m3s   172.18.0.2      spiderpool1111101355-worker          <none>           <none>            app.kubernetes.io/component=spiderpool-controller,app.kubernetes.io/instance=spiderpool,app.kubernetes.io/name=spiderpool,pod-template-hash=6f6fc9fd5d
kube-system        spiderpool-init                                              0/1     Completed          0             12m    172.18.0.2      spiderpool1111101355-worker          <none>           <none>            app.kubernetes.io/component=spiderpool-init,app.kubernetes.io/instance=spiderpool,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=spiderpool
ns2656-796769500   pod2656-796752500                                            1/1     Running            0             2m6s   10.51.9.2       spiderpool1111101355-worker          <none>           <none>  
```

```
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 460 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc001287958?})
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0x145
panic({0x27b7dc0, 0x2e4d1d0})
	/usr/local/go/src/runtime/panic.go:890 +0x262
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*SubnetController).syncControllerSubnet(0xc00012d260, {0x2e6bbf8, 0xc0011ec8d0}, 0xc000459250)
	/src/pkg/subnetmanager/subnet_informer.go:322 +0x496
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*SubnetController).syncHandler(0xc00012d260, {0x2e6bbf8, 0xc0011ec8d0}, {0xc0010d7848, 0x11})
	/src/pkg/subnetmanager/subnet_informer.go:274 +0x11c
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*SubnetController).processNextWorkItem.func1(0xc00012d260, 0xc001287db0, {0x26d93c0?, 0xc001208cd0})
	/src/pkg/subnetmanager/subnet_informer.go:251 +0x405
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*SubnetController).processNextWorkItem(0xc00012d260)
	/src/pkg/subnetmanager/subnet_informer.go:258 +0x6f
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*SubnetController).runWorker(0x4aaad7?)
	/src/pkg/subnetmanager/subnet_informer.go:224 +0x2f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00105d0f0)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x49
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000359458?, {0x2e517a0, 0xc00120ade0}, 0x1, 0xc000fda8a0)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xcf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x50?, 0x100000001?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x10e
k8s.io/apimachinery/pkg/util/wait.Until(0x420360?, 0x7f5375507800?, 0x0?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92 +0x49
created by github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*SubnetController).Run
	/src/pkg/subnetmanager/subnet_informer.go:213 +0x34a
```

**Comment by weizhoublue** [comment]
fix https://github.com/spidernet-io/spiderpool/pull/1038
