### ISSUE TITLE
CI failure: error, found error log!

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#1112]
Set title to be in the format CI: 
error, found error log !!!

Copy-paste the output the test failure.
```
---------spiderpool-controller-864c4f48df-wrz58--------
error, in spiderpool-controller-864c4f48df-wrz58, found error, Goroutine took lock !!!!!!!
{"level":"WARN","ts":"2022-11-28T11:43:29.995Z","logger":"Debug-Lock","caller":"lock/lock_debug.go:110","msg":"Goroutine took lock for more than 0.20 seconds","Seconds":0.381094313,"Goroutine":" 157"}


{"level":"DEBUG","ts":"2022-11-28T11:43:29.996Z","logger":"IP-GarbageCollection","caller":"gcmanager/tracePod_worker.go:55","msg":"sending signal to gc pod 'ns4049-797261545/deploy-1-4050-25375101-6874fd5d94-slgvv' IP"}
{"level":"DEBUG","ts":"2022-11-28T11:43:29.996Z","logger":"IP-GarbageCollection","caller":"gcmanager/pod_cache.go:68","msg":"delete deploy-1-4050-25375101-6874fd5d94-slgvv pod cache successfully"}
goroutine 157 [running]:
goroutine 157 runtime/debug.Stack()
goroutine 157 	/usr/local/go/src/runtime/debug/stack.go:24 +0x72
goroutine 157 github.com/spidernet-io/spiderpool/pkg/lock.(*internalRWMutex).Unlock(0xc00076e080)
goroutine 157 	/src/pkg/lock/lock_debug.go:59 +0xcd
goroutine 157 github.com/spidernet-io/spiderpool/pkg/gcmanager.(*PodDatabase).DeletePodEntry(0xc00076e080, {0xc000f73900, 0x10}, {0xc000f51890, 0x26})
goroutine 157 	/src/pkg/gcmanager/pod_cache.go:69 +0x305
goroutine 157 github.com/spidernet-io/spiderpool/pkg/gcmanager.(*SpiderGC).handlePodEntryForTracingTimeOut(0xc000156100, 0xc0010be480)
goroutine 157 	/src/pkg/gcmanager/tracePod_worker.go:56 +0xa68
goroutine 157 github.com/spidernet-io/spiderpool/pkg/gcmanager.(*SpiderGC).tracePodWorker(0xc000156100, {0x2e75330, 0xc000399880})
goroutine 157 	/src/pkg/gcmanager/tracePod_worker.go:30 +0x21e
goroutine 157 created by github.com/spidernet-io/spiderpool/pkg/gcmanager.(*SpiderGC).Start
goroutine 157 	/src/pkg/gcmanager/gc_manager.go:132 +0x1ba
{"level":"DEBUG","ts":"2022-11-28T11:43:30.060Z","logger":"SpiderIPPool-Informer","caller":"ippoolmanager/ippool_informer.go:500","msg":"update SpiderIPPool 'auto-deployment-ns4325-560101416-deploy-23-4326-646078621-v6-9e8e52e6894f' status TotalIPCount to '0' successfully"}
```
Upload the zip file generated from that test failure.
[ipv6Only-debuglog.txt (1).zip](https://github.com/spidernet-io/spiderpool/files/10103820/ipv6Only-debuglog.txt.1.zip)

Copy-paste the link of the CI build where that test failure has happen.
https://github.com/spidernet-io/spiderpool/actions/runs/3563923464/jobs/5987372727

Include any output from logs that you think may be relevant (to ease GitHub searches).
<img width="887" alt="image" src="https://user-images.githubusercontent.com/101157744/204283266-1b462b98-3885-4374-b841-d20f9c48d5c8.png">

**Comment by Icarus9913** [comment]
After testing, the logger will cost external time duration which will affect the lock.
https://github.com/spidernet-io/spiderpool/blob/053cf609ee6cf106750c9583da21acfe364d26e5/pkg/gcmanager/pod_cache.go#L56-L69
