### ISSUE TITLE
Night CI 2023-01-26: Failed, the locking period of function ApplyPodEntry is too long.

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#1290]
action url: https://github.com/spidernet-io/spiderpool/actions/runs/4018816470

**Comment by iiiceoo** [comment]
@Icarus9913, The locking period of function `ApplyPodEntry`  is too long.

```tex
{"level":"WARN","ts":"2023-01-26T21:28:33.767Z","logger":"Debug-Lock","caller":"lock/lock_debug.go:110","msg":"Goroutine took lock for more than 0.20 seconds","Seconds":0.212367701,"Goroutine":" 207"}
goroutine 207 [running]:
goroutine 207 runtime/debug.Stack()
goroutine 207 	/usr/local/go/src/runtime/debug/stack.go:24 +0x72
goroutine 207 github.com/spidernet-io/spiderpool/pkg/lock.(*internalRWMutex).Unlock(0xc00037e100)
goroutine 207 	/src/pkg/lock/lock_debug.go:59 +0xcd
goroutine 207 github.com/spidernet-io/spiderpool/pkg/gcmanager.(*PodDatabase).ApplyPodEntry(0xc00037e100, 0xc00070cbd0)
goroutine 207 	/src/pkg/gcmanager/pod_cache.go:113 +0x53f
goroutine 207 github.com/spidernet-io/spiderpool/pkg/gcmanager.(*SpiderGC).onPodDel(0xc0004a4000, {0x2a26780?, 0xc000e9b800})
goroutine 207 	/src/pkg/gcmanager/pod_informer.go:120 +0x2c6
goroutine 207 k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
goroutine 207 	/src/vendor/k8s.io/client-go/tools/cache/controller.go:246
goroutine 207 k8s.io/client-go/tools/cache.(*processorListener).run.func1()
goroutine 207 	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:820 +0x155
goroutine 207 k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0005dff18)
goroutine 207 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x49
goroutine 207 k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006a8de0?, {0x2e6c9c0, 0xc0005c1140}, 0x1, 0xc0006a8de0)
goroutine 207 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xcf
goroutine 207 k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4aab05?, 0x3b9aca00, 0x0, 0xc0?, 0xc0005dff50?)
goroutine 207 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x10e
goroutine 207 k8s.io/apimachinery/pkg/util/wait.Until(...)
goroutine 207 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92
goroutine 207 k8s.io/client-go/tools/cache.(*processorListener).run(0xc0004a4380?)
goroutine 207 	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:812 +0x79
goroutine 207 k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
goroutine 207 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:75 +0x74
goroutine 207 created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
goroutine 207 	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0xe5
```
