### ISSUE TITLE
`only_hardware` is set to true, Pod creation fails

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#1869]
**Describe the version**
version about:
1. spiderpool v0.6.0-rc0

**Describe the bug**
`only_hardware` is set to true, Pod creation fails

**Expected behavior**
succeed

**Screenshots and log**
```bash
Warning  FailedCreatePodSandBox  36s               kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "66263c2ef2231c1b9a51cc93963361dadd643f2f4c39f4ee5c4d81bf6d90f1da": plugin type="multus" name="multus-cni-network" failed (add): [ns034-71835136/xxxxxxxx-794496d489-6glf9/1b6f1e5b-0236-46ae-96a9-f6885aa4f2b6:test-multus-8eb47]: error adding container to network "test-multus-8eb47": netplugin failed: "panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17bbece]\n\ngoroutine 1 [running, locked to thread]:\ngithub.com/spidernet-io/spiderpool/cmd/coordinator/cmd.CmdAdd(0xc000238cb0)\n\t/src/cmd/coordinator/cmd/command_add.go:84 +0xc0e\ngithub.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc0003cdee8, 0xc000238cb0, {0x1e4b158, 0xc00032e9c0}, 0x1cb19c0)\n\t/src/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:166 +0x20a\ngithub.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc0003cdee8, 0x3?, 0x0?, 0x0?, {0x1e4b158, 0xc00032e9c0}, {0x1ba872b, 0xb})\n\t/src/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:219 +0x2ca\ngithub.com/containernetworking/cni/pkg/skel.PluginMainWithError(...)\n\t/src/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:273\ngithub.com/containernetworking/cni/pkg/skel.PluginMain(0x4069d9?, 0x60?, 0x0?, {0x1e4b158?, 0xc00032e9c0?}, {0x1ba872b?, 0xc0000061a0?})\n\t/src/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:288 +0xd1\nmain.main()\n\t/src/cmd/coordinator/main.go:23 +0x49\n"
```

**Additional context**

**Comment by ty-dc** [comment]
#1871
