### ISSUE TITLE
compile coordinator and subvlan do not have race flags enabled

### ISSUE THREAD

**Issue by cyclinder** [spidernet-io/spiderpool#1915]
**Describe the version**
version about:
1. spiderpool
2. kubernetes
3. what CNI and itsversion

**Describe the bug**

If we enable race flag at compile time, in the case of dual-stack and ipv6-only,  golang  runtime throws panic when call `netlink.RouteList` function, so we have to close it.

**How To Reproduce**
Steps to reproduce the issue:

**Expected behavior**

**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.

**Additional context**

https://github.com/containernetworking/plugins/issues/905
https://github.com/vishvananda/netlink/issues/877

**Comment by cyclinder** [comment]
```
Events:
  Type     Reason                  Age               From               Message
  ----     ------                  ----              ----               -------
  Normal   Scheduled               2m2s              default-scheduler  Successfully assigned kube-system/spiderdoctor-agent-5qchb to spiderpool0613065616-worker
  Normal   AddedInterface          119s              multus             Add eth0 [10.233.70.194/32 fd00:10:233:64:e0ff:7137:d5b2:4582/128] from kube-system/k8s-pod-network
  Warning  FailedCreatePodSandBox  65s               kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9e38f8bd6be816407332e0ba562f53d5af903b9aedaf160e4c2806f6b1844469": plugin type="multus" name="multus-cni-network" failed (add): [kube-system/spiderdoctor-agent-5qchb/afb227e4-86d9-41bd-b44f-f486cc68870d:macvlan-vlan100-overlay]: error adding container to network "macvlan-vlan100-overlay": netplugin failed: "fatal error: checkptr: misaligned pointer conversion\n\ngoroutine 63 [running, locked to thread]:\nruntime.throw({0x290e42c?, 0xc293df?})\n\t/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc0005e50c0 sp=0xc0005e5090 pc=0x470edd\nruntime.checkptrAlignment(0xc00044d160?, 0x14?, 0x388?)\n\t/usr/local/go/src/runtime/checkptr.go:20 +0x7d fp=0xc0005e50e0 sp=0xc0005e50c0 pc=0x43eadd\ngithub.com/vishvananda/netlink/nl.DeserializeRtNexthop(...)\n\t/src/vendor/github.com/vishvananda/netlink/nl/route_linux.go:51\ngithub.com/vishvananda/netlink.deserializeRoute.func1({0xc00044d174, 0x1c, 0x374})\n\t/src/vendor/github.com/vishvananda/netlink/route_linux.go:1131 +0x86 fp=0xc0005e5218 sp=0xc0005e50e0 pc=0xc2a266\ngithub.com/vishvananda/netlink.deserializeRoute({_, _, _})\n\t/src/vendor/github.com/vishvananda/netlink/route_linux.go:1189 +0x119f fp=0xc0005e55e8 sp=0xc0005e5218 pc=0xc293df\ngithub.com/vishvananda/netlink.(*Handle).RouteListFiltered(0x3ac9960?, 0x0, 0x0, 0x40)\n\t/src/vendor/github.com/vishvananda/netlink/route_linux.go:1038 +0x468 fp=0xc0005e5b28 sp=0xc0005e55e8 pc=0xc278a8\ngithub.com/vishvananda/netlink.(*Handle).RouteList(0x4ace85?, {0x0, 0x0}, 0x25ed900?)\n\t/src/vendor/github.com/vishvananda/netlink/route_linux.go:1003 +0xc7 fp=0xc0005e5cf8 sp=0xc0005e5b28 pc=0xc273a7\ngithub.com/vishvananda/netlink.RouteList(...)\n\t/src/vendor/github.com/vishvananda/netlink/route_linux.go:990\ngithub.com/spidernet-io/spiderpool/pkg/networking/networking.GetDefaultRouteInterface.func1({0xc000319bf0?, 0x0?})\n\t/src/pkg/networking/networking/route.go:215 +0x7f fp=0xc0005e5db8 sp=0xc0005e5cf8 pc=0x24d4cbf\ngithub.com/containernetworking/plugins/pkg/ns.(*netNS).Do.func1({0x2ca9ba0, 0xc00044e620})\n\t/src/vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go:197 +0x36f fp=0xc0005e5f30 sp=0xc0005e5db8 pc=0xbd5a8f\ngithub.com/containernetworking/plugins/pkg/ns.(*netNS).Do.func2()\n\t/src/vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go:218 +0xc9 fp=0xc0005e5fe0 sp=0xc0005e5f30 pc=0xbd5589\nruntime.goexit()\n\t/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005e5fe8 sp=0xc0005e5fe0 pc=0x4a9b21\ncreated by github.com/containernetworking/plugins/pkg/ns.(*netNS).Do\n\t/src/vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go:215 +0x518\n\ngoroutine 1 [semacquire, locked to thread]:\nruntime.gopark(0x46f933?, 0xc00055e5c0?, 0xc0?, 0xcf?, 0xc00055e5e0?)\n\t/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00055e[548](https://github.com/spidernet-io/spiderpool/actions/runs/5252177818/jobs/9488060117#step:11:549) sp=0xc00055e528 pc=0x473c16\nruntime.goparkunlock(...)\n\t/usr/local/go/src/runtime/proc.go:387\nruntime.semacquire1(0xc00005b358, 0x50?, 0x1, 0x0, 0x1?)\n\t/usr/local/go/src/runtime/sema.go:160 +0x20f fp=0xc00055e5b0 sp=0xc00055e548 pc=0x48680f\nsync.runtime_Semacquire(0xc00005b358?)\n\t/usr/local/go/src/runtime/sema.go:62 +0x27 fp=0xc00055e5e8 sp=0xc00055e5b0 pc=0x4a56e7\nsync.(*WaitGroup).Wait(0xc00005b350)\n\t/usr/local/go/src/sync/waitgroup.go:116 +0xa5 fp=0xc00055e618 sp=0xc00055e5e8 pc=0x4bd0c5\ngithub.com/containernetworking/plugins/pkg/ns.(*netNS).Do(0xc000319bf0, 0xc0000e36b0)\n\t/src/vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go:220 +0x525 fp=0xc00055e748 sp=0xc00055e618 pc=0xbd53c5\ngithub.com/spidernet-io/spiderpool/pkg/networking/networking.GetDefaultRouteInterface(0x0, {0xc00005a02c, 0x4}, {0x2ca9ba0, 0xc000319bf0})\n\t/src/pkg/networking/networking/route.go:214 +0x14c fp=0xc00055e7a8 sp=0xc00055e748 pc=0x24d4b8c\ngithub.com/spidernet-io/spiderpool/cmd/coordinator/cmd.(*coordinator).tunePodRoutes(0xc00056ab00, 0xc0001e93b0, {0x0, 0x0})\n\t/src/cmd/coordinator/cmd/utils.go:274 +0x492 fp=0xc00055eb40 sp=0xc00055e7a8 pc=0x24e8f92\ngithub.com/spidernet-io/spiderpool/cmd/coordinator/cmd.CmdAdd(0xc0001e9180)\n\t/src/cmd/coordinator/cmd/command_add.go:261 +0x606a fp=0xc00055fc48 sp=0xc00055eb40 pc=0x24e00ea\ngithub.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc00055fee8, 0xc0001e9180, {0x2c935f8, 0xc00011a7b0}, 0x29e6e08)\n\t/src/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:166 +0x34f fp=0xc00055fd00 sp=0xc00055fc48 pc=0xbc49cf\ngithub.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc00055fee8, 0x28c8ee0?, 0xc00008de01?, 0xc00008deb0?, {0x2c935f8, 0xc00011a7b0}, {0x28dd5a1, 0xb})\n\t/src/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:219 +0x214 fp=0xc00055fe58 sp=0xc00055fd00
```

**Comment by cyclinder** [comment]
fixed by https://github.com/spidernet-io/spiderpool/pull/1871
