### ISSUE TITLE
empty spidermultusconfig and crash

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2438]
create cr with empty spec, the webhook succeed, but there is no related  network-attachment-definitions

```
cat <<EOF | kubectl apply -f -
apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderMultusConfig
metadata:
  name: cilium
  namespace: kube-system
EOF

# kubectl get spidermultusconfig -A
NAMESPACE     NAME                      AGE
kube-system   calico-pod-network        6d23h
kube-system   cilium                    2m22s

# kubectl get network-attachment-definitions -A
NAMESPACE     NAME                      AGE
kube-system   calico-pod-network        6d23h

```

 then delte the cilium cr and recreate

```
cat <<EOF | kubectl apply -f -
apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderMultusConfig
metadata:
  name: cilium
  namespace: kube-system
spec:
  cniType: custom
  disableIPAM: false
  enableCoordinator: false
EOF



kube-system   spiderpool-controller-7b586b646-rsmx9        0/1     CrashLoopBackOff    6 (40s ago)        89m
```

```
# kubectl logs -n kube-system   spiderpool-controller-7b586b646-rsmx9
{"level":"INFO","ts":"2023-10-19T12:01:47.076Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:56","msg":"CommitVersion: 39eb7b49ed816fc244e95257eda4bd63c101f02f"}
{"level":"INFO","ts":"2023-10-19T12:01:47.077Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:59","msg":"CommitTime: 2023-10-12T20:40:54+08:00"}
{"level":"INFO","ts":"2023-10-19T12:01:47.077Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:62","msg":"AppVersion: main"}
{"level":"INFO","ts":"2023-10-19T12:01:47.077Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:67","msg":"Default max golang procs: 40"}
{"level":"INFO","ts":"2023-10-19T12:01:47.077Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:70","msg":"Change max golang procs to 40"}
{"level":"INFO","ts":"2023-10-19T12:01:47.077Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:77","msg":"Spiderpool-controller config: {CommitVersion:39eb7b49ed816fc244e95257eda4bd63c101f02f CommitTime:2023-10-12T20:40:54+08:00 AppVersion:main GoMaxProcs:8 ConfigPath:/tmp/spiderpool/config-map/conf.yml TlsServerCertPath:/etc/tls/tls.crt TlsServerKeyPath:/etc/tls/tls.key LogLevel:info EnableMetric:false EnableDebugLevelMetric:false MetricRenewPeriod:120 HttpPort:5720 MetricHttpPort:5721 WebhookPort:5722 GopsListenPort:5724 PyroscopeAddress: DefaultCniConfDir:/etc/cni/net.d ControllerPodNamespace:kube-system ControllerPodName:spiderpool-controller-7b586b646-rsmx9 LeaseDuration:15 LeaseRenewDeadline:10 LeaseRetryPeriod:2 LeaseRetryGap:1 IPPoolMaxAllocatedIPs:5000 SubnetInformerResyncPeriod:300 SubnetInformerWorkers:5 SubnetInformerMaxWorkqueueLength:10000 SubnetAppControllerWorkers:5 IPPoolInformerResyncPeriod:300 IPPoolInformerWorkers:3 IPPoolInformerMaxWorkQueueLength:10000 WorkQueueMaxRetries:500 WorkQueueRequeueDelayDuration:5 CoordinatorInformerResyncPeriod:60 EnableMultusConfig:true MultusConfigInformerResyncPeriod:60 EnableIPv4:true EnableIPv6:true EnableStatefulSet:true EnableSpiderSubnet:true ClusterSubnetDefaultFlexibleIPNum:1}"}
{"level":"INFO","ts":"2023-10-19T12:01:47.078Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:90","msg":"gops is listening on 127.0.0.1:5724"}
{"level":"INFO","ts":"2023-10-19T12:01:47.078Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:119","msg":"Begin to initialize spiderpool-controller metrics HTTP server"}
{"level":"INFO","ts":"2023-10-19T12:01:47.078Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:122","msg":"Begin to initialize spiderpool-controller runtime manager"}
{"level":"INFO","ts":"2023-10-19T12:01:47.091Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:254","msg":"Begin to initialize StatefulSet manager"}
{"level":"INFO","ts":"2023-10-19T12:01:47.092Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:150","msg":"Starting spiderpool-controller runtime manager"}
{"level":"INFO","ts":"2023-10-19T12:01:47.157Z","logger":"Lease-Lock-Election","caller":"election/lease_election.go:163","msg":"'kube-system/spiderpool-controller-leases/spiderpool-controller-7b586b646-rsmx9' is trying to elect"}
I1019 12:01:47.157744       1 leaderelection.go:250] attempting to acquire leader lease kube-system/spiderpool-controller-leases...
I1019 12:01:47.169387       1 leaderelection.go:260] successfully acquired lease kube-system/spiderpool-controller-leases
{"level":"INFO","ts":"2023-10-19T12:01:47.169Z","logger":"Lease-Lock-Election","caller":"election/lease_election.go:133","msg":"leader elected: kube-system/spiderpool-controller-leases/spiderpool-controller-7b586b646-rsmx9"}
{"level":"INFO","ts":"2023-10-19T12:01:47.258Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:160","msg":"Begin to initialize OpenAPI HTTP server"}
{"level":"INFO","ts":"2023-10-19T12:01:47.263Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:176","msg":"Begin to initialize IP GC Manager"}
{"level":"INFO","ts":"2023-10-19T12:01:47.264Z","logger":"spiderpool-controller","caller":"cmd/http_server.go:28","msg":"Serving spiderpool controller API at http://[[::]:5720]"}
{"level":"INFO","ts":"2023-10-19T12:01:47.266Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:179","msg":"Set spiderpool-controller Startup probe ready"}
{"level":"INFO","ts":"2023-10-19T12:01:47.266Z","logger":"IP-GarbageCollection","caller":"gcmanager/gc_manager.go:155","msg":"running IP garbage collection"}
{"level":"INFO","ts":"2023-10-19T12:01:47.266Z","logger":"IP-GarbageCollection","caller":"gcmanager/pod_informer.go:17","msg":"try to register pod informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.266Z","logger":"IP-GarbageCollection","caller":"gcmanager/tracePod_worker.go:28","msg":"starting trace pod worker"}
{"level":"INFO","ts":"2023-10-19T12:01:47.266Z","logger":"IP-GarbageCollection","caller":"gcmanager/tracePod_worker.go:74","msg":"Starting running 'releaseIPPoolIPExecutor'","IPPoolIP_Worker":3}
{"level":"INFO","ts":"2023-10-19T12:01:47.266Z","logger":"IP-GarbageCollection","caller":"gcmanager/pod_informer.go:49","msg":"create Pod informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.266Z","caller":"limiter/queue.go:135","msg":"Starting limiter"}
{"level":"INFO","ts":"2023-10-19T12:01:47.266Z","logger":"IP-GarbageCollection","caller":"gcmanager/tracePod_worker.go:74","msg":"Starting running 'releaseIPPoolIPExecutor'","IPPoolIP_Worker":2}
{"level":"INFO","ts":"2023-10-19T12:01:47.266Z","logger":"IP-GarbageCollection","caller":"gcmanager/tracePod_worker.go:74","msg":"Starting running 'releaseIPPoolIPExecutor'","IPPoolIP_Worker":1}
{"level":"INFO","ts":"2023-10-19T12:01:47.266Z","logger":"IP-GarbageCollection","caller":"gcmanager/scanAll_IPPool.go:57","msg":"receive CLI GC request, execute scan all right now!"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:447","msg":"Begin to set up Coordinator informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:459","msg":"Begin to set up IPPool informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"SpiderIPPool-Informer","caller":"ippoolmanager/ippool_informer.go:77","msg":"try to register SpiderIPPool informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:479","msg":"Begin to set up Subnet informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:492","msg":"Begin to set up auto-created IPPool controller"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"SpiderSubnet-Application-Controllers","caller":"applicationcontroller/app_controller.go:106","msg":"try to register SpiderSubnet App informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"spiderpool-controller","caller":"cmd/daemon.go:517","msg":"Begin to set up MultusConfig informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"MultusConfig-Informer","caller":"multuscniconfig/multusconfig_informer.go:73","msg":"try to register MultusConfig informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"MultusConfig-Informer","caller":"multuscniconfig/multusconfig_informer.go:105","msg":"create MultusConfig informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"SpiderIPPool-Informer","caller":"ippoolmanager/ippool_informer.go:109","msg":"create SpiderIPPool informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"Subnet-Informer","caller":"subnetmanager/subnet_informer.go:125","msg":"Initialize Dynamic informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"Coordinator-Informer","caller":"coordinatormanager/coordinator_informer.go:142","msg":"Initialize Coordinator informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"Subnet-Informer","caller":"subnetmanager/subnet_informer.go:129","msg":"Initialize Subnet informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"SpiderSubnet-Application-Controllers","caller":"applicationcontroller/app_controller.go:138","msg":"create SpiderSubnet App informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"SpiderSubnet-Application-Controllers","caller":"applicationinformers/deployment_informer.go:15","msg":"Setting up Deployment handlers"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"Subnet-Informer","caller":"subnetmanager/subnet_informer.go:250","msg":"Starting Subnet informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"Subnet-Informer","caller":"subnetmanager/subnet_informer.go:252","msg":"Waiting for informer caches to sync"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"SpiderSubnet-Application-Controllers","caller":"applicationinformers/replicaset_informer.go:15","msg":"Setting up ReplicaSet handlers"}
I1019 12:01:47.275730       1 shared_informer.go:311] Waiting for caches to sync for SpiderSubnet
I1019 12:01:47.275730       1 shared_informer.go:311] Waiting for caches to sync for SpiderCoordinator
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"SpiderSubnet-Application-Controllers","caller":"applicationinformers/statefulset_informer.go:15","msg":"Setting up StatefulSet handlers"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"SpiderSubnet-Application-Controllers","caller":"applicationinformers/daemonset_informer.go:15","msg":"Setting up DaemonSet handlers"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"SpiderSubnet-Application-Controllers","caller":"applicationinformers/job_informer.go:15","msg":"Setting up Job informer"}
{"level":"INFO","ts":"2023-10-19T12:01:47.275Z","logger":"SpiderSubnet-Application-Controllers","caller":"applicationinformers/cronjob_informer.go:15","msg":"Setting up CronJob handlers"}
I1019 12:01:47.458356       1 shared_informer.go:318] Caches are synced for SpiderCoordinator
I1019 12:01:47.458578       1 shared_informer.go:318] Caches are synced for SpiderSubnet
{"level":"INFO","ts":"2023-10-19T12:01:47.458Z","logger":"Subnet-Informer","caller":"subnetmanager/subnet_informer.go:257","msg":"Starting workers"}
{"level":"INFO","ts":"2023-10-19T12:01:47.458Z","logger":"Subnet-Informer","caller":"subnetmanager/subnet_informer.go:262","msg":"Starting dynamic informer worker"}
{"level":"INFO","ts":"2023-10-19T12:01:47.458Z","logger":"Subnet-Informer","caller":"subnetmanager/subnet_informer.go:265","msg":"Started workers"}
{"level":"INFO","ts":"2023-10-19T12:01:47.459Z","logger":"Coordinator-Informer","caller":"coordinatormanager/coordinator_informer.go:363","msg":"spidercoordinator change podCIDRType from auto to cilium","CoordinatorName":"default","Operation":"PROCESS"}
{"level":"INFO","ts":"2023-10-19T12:01:47.459Z","logger":"Coordinator-Informer","caller":"coordinatormanager/coordinator_informer.go:295","msg":"Succeed to SYNC","CoordinatorName":"default","Operation":"PROCESS"}
{"level":"INFO","ts":"2023-10-19T12:01:47.660Z","logger":"MultusConfig-Informer","caller":"multuscniconfig/multusconfig_informer.go:323","msg":"try to update net-attach-def &{{NetworkAttachmentDefinition k8s.cni.cncf.io/v1} {calico-pod-network  kube-system  a9a18d57-0c6d-4d0a-aec1-49472611e074 4779 1 2023-10-12 12:45:47 +0000 UTC <nil> <nil> map[] map[] [{spiderpool.spidernet.io/v2beta1 SpiderMultusConfig calico-pod-network 25c9e34c-c60f-4ba2-bab6-8d11df14343e 0xc00126676e 0xc00126676f}] [] [{spiderpool-controller Update k8s.cni.cncf.io/v1 2023-10-12 12:45:47 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"25c9e34c-c60f-4ba2-bab6-8d11df14343e\\\"}\":{}}},\"f:spec\":{\".\":{},\"f:config\":{}}} }]} {}}"}
E1019 12:01:47.666385       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 361 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1f2b5c0?, 0x3692d90})
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000857890?})
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1f2b5c0, 0x3692d90})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/spidernet-io/spiderpool/pkg/multuscniconfig.generateNetAttachDef({0xc00111dc26, 0x6}, 0xc0019146e0)
	/src/pkg/multuscniconfig/multusconfig_informer.go:351 +0xcb
github.com/spidernet-io/spiderpool/pkg/multuscniconfig.(*MultusConfigController).syncHandler(0xc000747ce0, {0x25a3e28, 0xc00005c050}, 0xc0019146e0)
	/src/pkg/multuscniconfig/multusconfig_informer.go:280 +0x197
github.com/spidernet-io/spiderpool/pkg/multuscniconfig.(*MultusConfigController).processNextWorkItem.func1({0x1e18c40?, 0xc000857890})
	/src/pkg/multuscniconfig/multusconfig_informer.go:214 +0x34e
github.com/spidernet-io/spiderpool/pkg/multuscniconfig.(*MultusConfigController).processNextWorkItem(0xc000747ce0)
	/src/pkg/multuscniconfig/multusconfig_informer.go:246 +0x5a
github.com/spidernet-io/spiderpool/pkg/multuscniconfig.(*MultusConfigController).runWorker(...)
	/src/pkg/multuscniconfig/multusconfig_informer.go:175
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x3691580?, {0x2584dc0, 0xc000383770}, 0x1, 0xc00064c300)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0008acfb0?, 0x3b9aca00, 0x0, 0x0?, 0x442ec5?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x9a76aa?, 0x0?, 0xc00089d710?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161 +0x25
created by github.com/spidernet-io/spiderpool/pkg/multuscniconfig.(*MultusConfigController).Run
	/src/pkg/multuscniconfig/multusconfig_informer.go:166 +0x18c
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c8a24b]

goroutine 361 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000857890?})
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x1f2b5c0, 0x3692d90})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/spidernet-io/spiderpool/pkg/multuscniconfig.generateNetAttachDef({0xc00111dc26, 0x6}, 0xc0019146e0)
	/src/pkg/multuscniconfig/multusconfig_informer.go:351 +0xcb
github.com/spidernet-io/spiderpool/pkg/multuscniconfig.(*MultusConfigController).syncHandler(0xc000747ce0, {0x25a3e28, 0xc00005c050}, 0xc0019146e0)
	/src/pkg/multuscniconfig/multusconfig_informer.go:280 +0x197
github.com/spidernet-io/spiderpool/pkg/multuscniconfig.(*MultusConfigController).processNextWorkItem.func1({0x1e18c40?, 0xc000857890})
	/src/pkg/multuscniconfig/multusconfig_informer.go:214 +0x34e
github.com/spidernet-io/spiderpool/pkg/multuscniconfig.(*MultusConfigController).processNextWorkItem(0xc000747ce0)
	/src/pkg/multuscniconfig/multusconfig_informer.go:246 +0x5a
github.com/spidernet-io/spiderpool/pkg/multuscniconfig.(*MultusConfigController).runWorker(...)
	/src/pkg/multuscniconfig/multusconfig_informer.go:175
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x3691580?, {0x2584dc0, 0xc000383770}, 0x1, 0xc00064c300)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0008acfb0?, 0x3b9aca00, 0x0, 0x0?, 0x442ec5?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x9a76aa?, 0x0?, 0xc00089d710?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161 +0x25
created by github.com/spidernet-io/spiderpool/pkg/multuscniconfig.(*MultusConfigController).Run
	/src/pkg/multuscniconfig/multusconfig_informer.go:166 +0x18c
```

(1) empty cr issue
(2) crash issue

**Comment by ty-dc** [comment]
#2444
