### ISSUE TITLE
coordinator informer panic

### ISSUE THREAD

**Issue by Icarus9913** [spidernet-io/spiderpool#3263]
### Spiderpool Version

main

### Bug Type

Coordinator

### Main CNI

/

### What happened?

kubernetes version: `v1.27.0`
spiderpool main branch

```text
{"level":"INFO","ts":"2024-02-29T09:15:07.835Z","logger":"Subnet-Informer","caller":"subnetmanager/subnet_informer.go:294","msg":"Succeed to SYNC","SubnetName":"default-v4-subnet","Operation":"PROCESS"}
{"level":"INFO","ts":"2024-02-29T09:15:07.835Z","logger":"Subnet-Informer","caller":"subnetmanager/subnet_informer.go:294","msg":"Succeed to SYNC","SubnetName":"default-v6-subnet","Operation":"PROCESS"}
I0229 09:15:07.838840       1 shared_informer.go:318] Caches are synced for SpiderCoordinator
{"level":"INFO","ts":"2024-02-29T09:15:07.848Z","logger":"Coordinator-Informer","caller":"coordinatormanager/coordinator_informer.go:463","msg":"Trying to fetch the ClusterCIDR from kube-system/kubeadm-config","Event Key":"SpiderCoordinator/default","Operation":"PROCESS"}
{"level":"INFO","ts":"2024-02-29T09:15:07.848Z","logger":"Coordinator-Informer","caller":"coordinatormanager/coordinator_informer.go:484","msg":"Detect podCIDRType is: none, try to update podCIDR","Event Key":"SpiderCoordinator/default","Operation":"PROCESS"}
E0229 09:15:07.849097       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 481 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x209bbe0?, 0x399a8a0})
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00121e110?})
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x209bbe0, 0x399a8a0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/spidernet-io/spiderpool/pkg/coordinatormanager.(*CoordinatorController).updateServiceCIDR(0xc0008cc0f0, 0xc00059ac40, 0xc0008688c0)
	/src/pkg/coordinatormanager/coordinator_informer.go:709 +0x5d
github.com/spidernet-io/spiderpool/pkg/coordinatormanager.(*CoordinatorController).updatePodAndServerCIDR(0xc0008cc0f0, {0x27b0838, 0xc001330150}, 0xc00059ac40, 0xc00121a000?)
	/src/pkg/coordinatormanager/coordinator_informer.go:507 +0xb8b
github.com/spidernet-io/spiderpool/pkg/coordinatormanager.(*CoordinatorController).syncHandler(0xc0008cc0f0, {0x27b0838, 0xc001330150})
	/src/pkg/coordinatormanager/coordinator_informer.go:433 +0xe6
github.com/spidernet-io/spiderpool/pkg/coordinatormanager.(*CoordinatorController).processNextWorkItem(0xc0008cc0f0, {0x27b0838, 0xc0008200c0})
	/src/pkg/coordinatormanager/coordinator_informer.go:414 +0x30c
github.com/spidernet-io/spiderpool/pkg/coordinatormanager.(*CoordinatorController).runWorker(...)
	/src/pkg/coordinatormanager/coordinator_informer.go:398
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:259 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1f259a0?, {0x278ffc0, 0xc0013300f0}, 0x1, 0xc00054e540)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1?, 0x3b9aca00, 0x0, 0x90?, 0x200000000?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x89
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x27b0838, 0xc0008200c0}, 0xc0006f9e50, 0xc000779080?, 0x0?, 0x0?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:259 +0x99
k8s.io/apimachinery/pkg/util/wait.UntilWithContext({0x27b0838?, 0xc0008200c0?}, 0xc000611768?, 0xc000611778?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:170 +0x2b
created by github.com/spidernet-io/spiderpool/pkg/coordinatormanager.(*CoordinatorController).run
	/src/pkg/coordinatormanager/coordinator_informer.go:389 +0x285
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1db933d]

goroutine 481 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00121e110?})
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x209bbe0, 0x399a8a0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/spidernet-io/spiderpool/pkg/coordinatormanager.(*CoordinatorController).updateServiceCIDR(0xc0008cc0f0, 0xc00059ac40, 0xc0008688c0)
	/src/pkg/coordinatormanager/coordinator_informer.go:709 +0x5d
github.com/spidernet-io/spiderpool/pkg/coordinatormanager.(*CoordinatorController).updatePodAndServerCIDR(0xc0008cc0f0, {0x27b0838, 0xc001330150}, 0xc00059ac40, 0xc00121a000?)
	/src/pkg/coordinatormanager/coordinator_informer.go:507 +0xb8b
github.com/spidernet-io/spiderpool/pkg/coordinatormanager.(*CoordinatorController).syncHandler(0xc0008cc0f0, {0x27b0838, 0xc001330150})
	/src/pkg/coordinatormanager/coordinator_informer.go:433 +0xe6
github.com/spidernet-io/spiderpool/pkg/coordinatormanager.(*CoordinatorController).processNextWorkItem(0xc0008cc0f0, {0x27b0838, 0xc0008200c0})
	/src/pkg/coordinatormanager/coordinator_informer.go:414 +0x30c
github.com/spidernet-io/spiderpool/pkg/coordinatormanager.(*CoordinatorController).runWorker(...)
	/src/pkg/coordinatormanager/coordinator_informer.go:398
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:259 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1f259a0?, {0x278ffc0, 0xc0013300f0}, 0x1, 0xc00054e540)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1?, 0x3b9aca00, 0x0, 0x90?, 0x200000000?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x89
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x27b0838, 0xc0008200c0}, 0xc0006f9e50, 0xc000779080?, 0x0?, 0x0?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:259 +0x99
k8s.io/apimachinery/pkg/util/wait.UntilWithContext({0x27b0838?, 0xc0008200c0?}, 0xc000611768?, 0xc000611778?)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:170 +0x2b
created by github.com/spidernet-io/spiderpool/pkg/coordinatormanager.(*CoordinatorController).run
	/src/pkg/coordinatormanager/coordinator_informer.go:389 +0x285
```

### What did you expect to happen?

/

### How to reproduce it (as minimally and precisely as possible)

/

**Comment by cyclinder** [comment]
Where is the issue you hit? In the CI or your local machine?

**Comment by Icarus9913** [comment]
> Where is the issue you hit? In the CI or your local machine?

my local environment

**Comment by cyclinder** [comment]
Surprisingly, my local k8s version is 1.27.1 and it runs fine and PR CIy has found no problems. 

@ty-dc How our PR CI passed, with some possible enhancements.

**Comment by cyclinder** [comment]
```
➜  ~ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"clean", BuildDate:"2022-09-14T19:49:27Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-05-12T19:03:40Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.27) exceeds the supported minor version skew of +/-1
➜  ~ kubectl get servicecidr -A
error: the server doesn't have a resource type "servicecidr"
➜  ~ kubectl get po -n kube-system -o wide | grep controller
calico-kube-controllers-f6fb49d4c-5v2sn        1/1     Running     0             43h   10.233.104.193   spider-worker          <none>           <none>
kube-controller-manager-spider-control-plane   1/1     Running     2 (42h ago)   43h   172.25.0.2       spider-control-plane   <none>           <none>
spiderpool-controller-78497789dd-j8ggn         1/1     Running     0             15h   172.25.0.2       spider-control-plane   <none>           <none>
spiderpool-controller-78497789dd-z9vtw         1/1     Running     0             15h   172.25.0.3       spider-worker          <none>           <none>
```

**Comment by cyclinder** [comment]
maybe we need a `call_e2e_dual_for_low_k8s`, just like a `call_e2e_dual_for_low_kernel`

**Comment by ty-dc** [comment]
> maybe we need a `call_e2e_dual_for_low_k8s`, just like a `call_e2e_dual_for_low_kernel`

Great suggestion, I'll add it later.
