### ISSUE TITLE
Auto-recycle IPPools failed and observed a panic: "makeslice: len out of range"

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#906]
**Describe the version**
version about:
spiderpool
- v0.2.2

**Describe the bug**
Observed a panic: "makeslice: len out of range" (runtime error: makeslice: len out of range)
panic: runtime error: makeslice: len out of range [recovered]

**Output of the failure**
```
{"level":"DEBUG","ts":"2022-10-19T09:12:27.811Z","logger":"Subnet-Manager","caller":"subnetmanager/subnet_manager.go:257","msg":"no need to scale subnet 'v6-ss-1032-850295098' IPPool 'auto-deployment-ns1031-663811671-deploy18-1033-500462605-v6-1666170643'"}
{"level":"DEBUG","ts":"2022-10-19T09:12:27.812Z","logger":"Subnet-Manager","caller":"subnetmanager/deployment_controller.go:48","msg":"onDeploymentAdd: deployment '&Deployment{ObjectMeta:{deploy17-1033-500201180  ns1031-663811671  67ef9cf9-cf25-48d5-a6ff-8a13ddff29c5 184804 3 2022-10-19 09:10:35 +0000 UTC <nil> <nil> map[] map[deployment.kubernetes.io/revision:1] [] []  [{subnet.test Update apps/v1 2022-10-19 09:10:35 +0000 UTC FieldsV1 {\"f:spec\":{\"f:progressDeadlineSeconds\":{},\"f:replicas\":{},\"f:revisionHistoryLimit\":{},\"f:selector\":{},\"f:strategy\":{\"f:rollingUpdate\":{\".\":{},\"f:maxSurge\":{},\"f:maxUnavailable\":{}},\"f:type\":{}},\"f:template\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:spiderpool.spidernet.io/flexible-ip-number\":{},\"f:spiderpool.spidernet.io/spider-subnet-v4\":{},\"f:spiderpool.spidernet.io/spider-subnet-v6\":{}},\"f:labels\":{\".\":{},\"f:app\":{}}},\"f:spec\":{\"f:containers\":{\"k:{\\\"name\\\":\\\"samplepod\\\"}\":{\".\":{},\"f:command\":{},\"f:image\":{},\"f:imagePullPolicy\":{},\"f:name\":{},\"f:resources\":{},\"f:terminationMessagePath\":{},\"f:terminationMessagePolicy\":{}}},\"f:dnsPolicy\":{},\"f:nodeSelector\":{},\"f:restartPolicy\":{},\"f:schedulerName\":{},\"f:securityContext\":{},\"f:terminationGracePeriodSeconds\":{}}}}} } {kube-controller-manager Update apps/v1 2022-10-19 09:10:40 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:deployment.kubernetes.io/revision\":{}}},\"f:status\":{\"f:conditions\":{\".\":{},\"k:{\\\"type\\\":\\\"Available\\\"}\":{\".\":{},\"f:lastTransitionTime\":{},\"f:lastUpdateTime\":{},\"f:message\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}},\"k:{\\\"type\\\":\\\"Progressing\\\"}\":{\".\":{},\"f:lastTransitionTime\":{},\"f:lastUpdateTime\":{},\"f:message\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}}},\"f:observedGeneration\":{},\"f:replicas\":{},\"f:unavailableReplicas\":{},\"f:updatedReplicas\":{}}} status}]},Spec:DeploymentSpec{Replicas:*1,Selector:&v1.LabelSelector{MatchLabels:map[string]string{app: deploy17-1033-500201180,},MatchExpressions:[]LabelSelectorRequirement{},},Template:{{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[app:deploy17-1033-500201180] map[spiderpool.spidernet.io/flexible-ip-number:0 spiderpool.spidernet.io/spider-subnet-v4:v4-ss-1032-850155781 spiderpool.spidernet.io/spider-subnet-v6:v6-ss-1032-850295098] [] []  []} {[] [] [{samplepod alpine [/bin/ash -c sleep infinity] []  [] [] [] {map[] map[]} [] [] nil nil nil nil /dev/termination-log File IfNotPresent nil false false false}] [] Always 0xc001359428 <nil> ClusterFirst map[kubernetes.io/hostname:NonExistentNode1033-492965142]   <nil>  false false false <nil> PodSecurityContext{SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:nil,RunAsGroup:nil,Sysctls:[]Sysctl{},WindowsOptions:nil,FSGroupChangePolicy:nil,SeccompProfile:nil,} []   nil default-scheduler [] []  <nil> nil [] <nil> <nil> <nil> map[] [] <nil> nil}},Strategy:DeploymentStrategy{Type:RollingUpdate,RollingUpdate:&RollingUpdateDeployment{MaxUnavailable:25%,MaxSurge:25%,},},MinReadySeconds:0,RevisionHistoryLimit:*10,Paused:false,ProgressDeadlineSeconds:*600,},Status:DeploymentStatus{ObservedGeneration:3,Replicas:1,UpdatedReplicas:1,AvailableReplicas:0,UnavailableReplicas:1,Conditions:[]DeploymentCondition{DeploymentCondition{Type:Available,Status:False,Reason:MinimumReplicasUnavailable,Message:Deployment does not have minimum availability.,LastUpdateTime:2022-10-19 09:10:40 +0000 UTC,LastTransitionTime:2022-10-19 09:10:40 +0000 UTC,},DeploymentCondition{Type:Progressing,Status:True,Reason:ReplicaSetUpdated,Message:ReplicaSet \"deploy17-1033-500201180-5986b89bd6\" is progressing.,LastUpdateTime:2022-10-19 09:10:40 +0000 UTC,LastTransitionTime:2022-10-19 09:10:36 +0000 UTC,},},ReadyReplicas:0,CollisionCount:nil,},}', SpiderSubnet configuration '{subnetManagerV4:v4-ss-1032-850155781 subnetManagerV6:v6-ss-1032-850295098 flexibleIPNum:0xc001359458 assignIPNum:0 reclaimIPPool:true}'"}
E1019 09:12:27.962133       1 runtime.go:79] Observed a panic: "makeslice: len out of range" (runtime error: makeslice: len out of range)
goroutine 458 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x278cf60?, 0x2e13970?})
        /src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0xf3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
        /src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0xb0
panic({0x278cf60, 0x2e13970})
        /usr/local/go/src/runtime/panic.go:890 +0x262
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*subnetManager).GenerateIPsFromSubnet(0xc00019cd20?, {0x2e32168, 0xc0001b8018}, {0xc001240888, 0x14}, 0xffffffffffffffff)
        /src/pkg/subnetmanager/subnet_manager.go:106 +0x185
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*subnetManager).CheckScaleIPPool(0xc00075f800, {0x2e32168, 0xc0001b8018}, 0xc001039340, {0xc001240888, 0x14}, 0x1)
        /src/pkg/subnetmanager/subnet_manager.go:263 +0x647
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*subnetManager).reconcile.func1({0x2e32168, 0xc0001b8018}, 0xc001039340, {0xc001240888, 0x14}, 0xa?)
        /src/pkg/subnetmanager/subnet_controller.go:74 +0x179
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*subnetManager).reconcile(0xc00075f800, {0x2e32168, 0xc0001b8018}, 0xc0010b3c00, {0x2a13f23, 0xa}, {0x2e47aa0, 0xc0012db200}, 0xc001368780, 0x1)
        /src/pkg/subnetmanager/subnet_controller.go:88 +0x205
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*subnetManager).onDeploymentAdd(0xc00075f800?, {0x29dc040?, 0xc001044480})
        /src/pkg/subnetmanager/deployment_controller.go:51 +0x390
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /src/vendor/k8s.io/client-go/tools/cache/controller.go:232
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:818 +0x2b4
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000073f18)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x49
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0012cc420?, {0x2e17f80, 0xc000814150}, 0x1, 0xc0012cc420)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xcf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4aab05?, 0x3b9aca00, 0x0, 0x80?, 0xc000073f50?)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x10e
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0007bea80?)
        /src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:812 +0x79
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x74
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0xe5
panic: runtime error: makeslice: len out of range [recovered]
        panic: runtime error: makeslice: len out of range

goroutine 458 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
        /src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0x145
panic({0x278cf60, 0x2e13970})
        /usr/local/go/src/runtime/panic.go:890 +0x262
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*subnetManager).GenerateIPsFromSubnet(0xc00019cd20?, {0x2e32168, 0xc0001b8018}, {0xc001240888, 0x14}, 0xffffffffffffffff)
        /src/pkg/subnetmanager/subnet_manager.go:106 +0x185
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*subnetManager).CheckScaleIPPool(0xc00075f800, {0x2e32168, 0xc0001b8018}, 0xc001039340, {0xc001240888, 0x14}, 0x1)
        /src/pkg/subnetmanager/subnet_manager.go:263 +0x647
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*subnetManager).reconcile.func1({0x2e32168, 0xc0001b8018}, 0xc001039340, {0xc001240888, 0x14}, 0xa?)
        /src/pkg/subnetmanager/subnet_controller.go:74 +0x179
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*subnetManager).reconcile(0xc00075f800, {0x2e32168, 0xc0001b8018}, 0xc0010b3c00, {0x2a13f23, 0xa}, {0x2e47aa0, 0xc0012db200}, 0xc001368780, 0x1)
        /src/pkg/subnetmanager/subnet_controller.go:88 +0x205
github.com/spidernet-io/spiderpool/pkg/subnetmanager.(*subnetManager).onDeploymentAdd(0xc00075f800?, {0x29dc040?, 0xc001044480})
        /src/pkg/subnetmanager/deployment_controller.go:51 +0x390
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /src/vendor/k8s.io/client-go/tools/cache/controller.go:232
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:818 +0x2b4
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000073f18)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x49
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0012cc420?, {0x2e17f80, 0xc000814150}, 0x1, 0xc0012cc420)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xcf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4aab05?, 0x3b9aca00, 0x0, 0x80?, 0xc000073f50?)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x10e
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0007bea80?)
        /src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:812 +0x79
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x74
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0xe5
```

**Additional**
During my test, I created the deployment and it automatically created the ippool, when I continued I first deleted the namespace (not deleting the deployment at this point) and after some time I observed that the automatically created ippool had not been recycled. At this point these deployments have been recalled.

**Some data presentation**
- kubectl get pods -A

```
NAMESPACE     NAME                                           READY   STATUS      RESTARTS        AGE
default       test-pod-68df9fd57b-qrwcd                      1/1     Running     0               28h
kube-system   coredns-64897985d-4cmp2                        1/1     Running     0               28h
kube-system   coredns-64897985d-qw45f                        1/1     Running     0               28h
kube-system   etcd-spider-control-plane                      1/1     Running     0               28h
kube-system   kube-apiserver-spider-control-plane            1/1     Running     0               28h
kube-system   kube-controller-manager-spider-control-plane   1/1     Running     0               28h
kube-system   kube-multus-ds-bjx8g                           1/1     Running     0               28h
kube-system   kube-multus-ds-v74qp                           1/1     Running     0               28h
kube-system   kube-proxy-fzb6l                               1/1     Running     0               28h
kube-system   kube-proxy-hwsh4                               1/1     Running     0               28h
kube-system   kube-scheduler-spider-control-plane            1/1     Running     1 (3h28m ago)   28h
kube-system   spiderpool-agent-4z8j7                         1/1     Running     1 (11h ago)     28h
kube-system   spiderpool-agent-755rr                         1/1     Running     1 (7h57m ago)   28h
kube-system   spiderpool-controller-8475b579bd-7m5fb         1/1     Running     4 (58m ago)     28h
kube-system   spiderpool-controller-8475b579bd-cl7xr         1/1     Running     6 (58m ago)     28h
kube-system   spiderpool-init                                0/1     Completed   0               28h
```
- kubectl get sp
```
NAME                                                                     VERSION   SUBNET                    ALLOCATED-IP-COUNT   TOTAL-IP-COUNT   DISABLE
auto-deployment-ns1031-663811671-deploy1-1033-494375818-v4-1666170650    4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy1-1033-494375818-v6-1666170650    6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy10-1033-497223973-v4-1666170658   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy10-1033-497223973-v6-1666170659   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy11-1033-498662120-v4-1666170657   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy11-1033-498662120-v6-1666170657   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy12-1033-498025009-v4-1666170653   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy12-1033-498025009-v6-1666170653   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy13-1033-498363588-v4-1666170653   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy13-1033-498363588-v6-1666170655   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy14-1033-499194307-v4-1666170659   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy14-1033-499194307-v6-1666170660   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy15-1033-500808790-v4-1666170637   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy15-1033-500808790-v6-1666170637   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy16-1033-499775672-v4-1666170638   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy16-1033-499775672-v6-1666170638   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy17-1033-500201180-v4-1666170649   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy17-1033-500201180-v6-1666170649   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy18-1033-500462605-v4-1666170640   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy18-1033-500462605-v6-1666170643   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy19-1033-502312876-v4-1666170651   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy19-1033-502312876-v6-1666170651   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy2-1033-494743223-v4-1666170656    4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy2-1033-494743223-v6-1666170657    6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy20-1033-501170599-v4-1666170635   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy20-1033-501170599-v6-1666170636   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy21-1033-501425596-v4-1666170645   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy21-1033-501425596-v6-1666170645   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy22-1033-501795081-v4-1666170655   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy22-1033-501795081-v6-1666170655   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy23-1033-502077233-v4-1666170653   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy23-1033-502077233-v6-1666170653   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy24-1033-502572144-v4-1666170637   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy24-1033-502572144-v6-1666170637   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy25-1033-503046032-v4-1666170652   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy25-1033-503046032-v6-1666170652   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy26-1033-499397757-v4-1666170645   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy26-1033-499397757-v6-1666170645   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy27-1033-505171404-v4-1666170651   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy27-1033-505171404-v6-1666170651   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy28-1033-504648945-v4-1666170649   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy28-1033-504648945-v6-1666170649   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy29-1033-504869799-v4-1666170639   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy29-1033-504869799-v6-1666170640   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy3-1033-494987984-v4-1666170638    4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy3-1033-494987984-v6-1666170638    6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy30-1033-493296176-v4-1666170639   4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy30-1033-493296176-v6-1666170639   6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy4-1033-495447243-v4-1666170643    4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy4-1033-495447243-v6-1666170644    6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy5-1033-495261503-v4-1666170660    4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy5-1033-495261503-v6-1666170660    6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy6-1033-497723202-v4-1666170658    4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy6-1033-497723202-v6-1666170658    6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy7-1033-495977096-v4-1666170656    4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy7-1033-495977096-v6-1666170656    6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy8-1033-496293548-v4-1666170659    4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy8-1033-496293548-v6-1666170659    6         fd00:4be2::/120           0                    2                false
auto-deployment-ns1031-663811671-deploy9-1033-496772553-v4-1666170643    4         10.231.102.0/24           0                    2                false
auto-deployment-ns1031-663811671-deploy9-1033-496772553-v6-1666170643    6         fd00:4be2::/120           0                    2                false
auto-deployment-ns5426-866635075-deploy1-5428-392438986-v4-1666162470    4         10.0.134.0/24             0                    2                false
auto-deployment-ns5426-866635075-deploy1-5428-392438986-v6-1666162470    6         fd00:9bdd::/120           0                    2                false
auto-deployment-ns5426-866635075-deploy2-5428-392855883-v4-1666162471    4         10.0.134.0/24             0                    2                false
auto-deployment-ns5426-866635075-deploy2-5428-392855883-v6-1666162471    6         fd00:9bdd::/120           0                    2                false
auto-deployment-ns5426-866635075-deploy3-5428-393169485-v4-1666162468    4         10.0.134.0/24             0                    2                false
auto-deployment-ns5426-866635075-deploy3-5428-393169485-v6-1666162469    6         fd00:9bdd::/120           0                    2                false
auto-deployment-ns5426-866635075-deploy4-5428-391962711-v4-1666162470    4         10.0.134.0/24             0                    2                false
auto-deployment-ns5426-866635075-deploy4-5428-391962711-v6-1666162470    6         fd00:9bdd::/120           0                    2                false
auto-deployment-ns5426-866635075-deploy5-5428-393343866-v4-1666162469    4         10.0.134.0/24             0                    2                false
auto-deployment-ns5426-866635075-deploy5-5428-393343866-v6-1666162469    6         fd00:9bdd::/120           0                    2                false
default-v4-ippool                                                        4         172.18.0.0/16             4                    253              false
default-v6-ippool                                                        6         fc00:f853:ccd:e793::/64   4                    253              false
```

**As you can see from these data, the deployment does not exist, but the pool has not been reclaimed; Also, the controller pod had a reboot**

**Comment by ty-dc** [comment]
Another phenomenon is that after I manually delete these undeleted ippools, the subnets associated with them are also automatically deleted. I previously performed an action to delete the subnet but it was hung (pool was not deleted) so now deleting the pool retriggers it again? I may have missed some details
